-- MySQL Script generated by MySQL Workbench
-- Sat Aug  2 12:16:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema appSchema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appSchema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appSchema` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `appSchema` ;

-- -----------------------------------------------------
-- Table `appSchema`.`Cusum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`Cusum` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`Cusum` (
  `idCusum` INT NOT NULL AUTO_INCREMENT,
  `tipoP` ENUM('intubacion orotraqueal', 'intubacion nasotraqueal', 'mascara laringea', 'anestesia subaracnoidea') NOT NULL,
  `valorCusum` DECIMAL(10,4) NOT NULL,
  `resultado` ENUM('Sí', 'No') NOT NULL,
  `fecha` DATETIME NOT NULL,
  `observacion` MEDIUMTEXT NOT NULL,
  `Estudiante_id_codigoEstudiantil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCusum`, `Estudiante_id_codigoEstudiantil`),
  INDEX `fk_Cusum_Estudiante1_idx` (`Estudiante_id_codigoEstudiantil` ASC) VISIBLE,
  UNIQUE INDEX `tipoP_UNIQUE` (`tipoP` ASC) VISIBLE,
  CONSTRAINT `fk_Cusum_Estudiante1`
    FOREIGN KEY (`Estudiante_id_codigoEstudiantil`)
    REFERENCES `appSchema`.`Estudiante` (`id_codigoEstudiantil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`Estudiante` (
  `id_codigoEstudiantil` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `número de Documento` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseñaCifrada` VARCHAR(45) NOT NULL,
  `fechaCreación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_codigoEstudiantil`),
  UNIQUE INDEX `id_codigoEstudiantil_UNIQUE` (`id_codigoEstudiantil` ASC) VISIBLE,
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC) VISIBLE,
  UNIQUE INDEX `contraseñaCifrada_UNIQUE` (`contraseñaCifrada` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`Pacientes` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`Pacientes` (
  `idDocumento_p` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `género` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `talla` FLOAT NOT NULL,
  `IMC` DOUBLE NOT NULL,
  `aperturaOral` ENUM("<4 cm", ">4cm") NOT NULL,
  `distanciaTiro` ENUM("< 6cm", "> 6cm") NULL,
  `dentadura` ENUM("Completa", "Parcial", "Protesis fija", "Protesis removible") NOT NULL,
  `antecedentes` VARCHAR(200) NULL,
  `asa` ENUM("I", "II", "III", "IV") NOT NULL,
  PRIMARY KEY (`idDocumento_p`),
  UNIQUE INDEX `idDocumento_p_UNIQUE` (`idDocumento_p` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`anestesia_subaracnoidea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`anestesia_subaracnoidea` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`anestesia_subaracnoidea` (
  `idProcedimiento` INT NOT NULL,
  `escoliosis` ENUM('Sí', 'No') NULL,
  `grado_espalda` ENUM('I', 'II', 'III', 'IV') NULL,
  `uso_ecografo` ENUM('Sí', 'No') NULL,
  `tipo_spinocath` ENUM('Punta lápiz', 'Cortante') NULL,
  `grosor_spinocath` VARCHAR(10) NULL,
  `nivel_puncion` VARCHAR(10) NULL,
  `tipo_abordaje` ENUM('Medial', 'Paramediana', 'Taylor') NULL,
  `numero_intentos` INT NULL,
  `cambio_abordaje` ENUM('No', 'Medial a paramediana', 'Paramediana a medial') NULL,
  `exito` ENUM('Sí', 'No') NULL,
  PRIMARY KEY (`idProcedimiento`),
  CONSTRAINT `procedimiento`
    FOREIGN KEY (`idProcedimiento`)
    REFERENCES `appSchema`.`procedimiento` (`idProcedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`cirugia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`cirugia` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`cirugia` (
  `idcirugia` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(200) NULL,
  `celeridad` ENUM("Programada", "Urgencia", "Emergencia") NOT NULL,
  `ayuno` ENUM("Completo", "Incompleto") NOT NULL,
  PRIMARY KEY (`idcirugia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`intubacion_oro/nasotraqueal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`intubacion_oro/nasotraqueal` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`intubacion_oro/nasotraqueal` (
  `idProcedimiento` INT NOT NULL,
  `cormack` ENUM('I', 'II', 'IIIa', 'IIIb', 'IV') NULL,
  `dispositivo_visualizacion` ENUM('Laringoscopio', 'Videolaringoscopio', 'Manual') NULL,
  `tipo_induccion` ENUM('Convencional', 'Rápida', 'Despierto') NULL,
  `tipo_tubo` ENUM('Con balón', 'Sin balón', 'Combitubo') NULL,
  `tamano_tubo` INT NULL,
  `numero_intentos` INT NULL,
  `exito` ENUM('Sí', 'No') NULL,
  PRIMARY KEY (`idProcedimiento`),
  CONSTRAINT `procedimiento1`
    FOREIGN KEY (`idProcedimiento`)
    REFERENCES `appSchema`.`procedimiento` (`idProcedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`mascara_laringea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`mascara_laringea` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`mascara_laringea` (
  `idProcedimiento` INT NOT NULL,
  `cormack` ENUM('I', 'II', 'IIIa', 'IIIb', 'IV') NULL,
  `tipo_dispositivo` ENUM('Primera generación', 'Segunda generación', 'Tercera generación', 'Cuarta generación') NULL,
  `numero_intentos` INT NULL,
  `exito` ENUM('Sí', 'No') NULL,
  PRIMARY KEY (`idProcedimiento`),
  CONSTRAINT `procedimiento`
    FOREIGN KEY (`idProcedimiento`)
    REFERENCES `appSchema`.`procedimiento` (`idProcedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appSchema`.`procedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appSchema`.`procedimiento` ;

CREATE TABLE IF NOT EXISTS `appSchema`.`procedimiento` (
  `idProcedimiento` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('orotraqueal', 'nasotraqueal', 'mascara_laringea', 'subaracnoidea') NOT NULL,
  `fechaHora` DATETIME NULL,
  `codigoEstudiante` VARCHAR(45) NULL,
  `codigoPaciente` VARCHAR(45) NULL,
  `codigoCirugia` INT NULL,
  INDEX `estudiante_idx` (`codigoEstudiante` ASC) VISIBLE,
  INDEX `paciente_idx` (`codigoPaciente` ASC) VISIBLE,
  INDEX `cirugia_idx` (`codigoCirugia` ASC) VISIBLE,
  PRIMARY KEY (`idProcedimiento`),
  CONSTRAINT `estudiante`
    FOREIGN KEY (`codigoEstudiante`)
    REFERENCES `appSchema`.`Estudiante` (`id_codigoEstudiantil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paciente`
    FOREIGN KEY (`codigoPaciente`)
    REFERENCES `appSchema`.`Pacientes` (`idDocumento_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cirugia`
    FOREIGN KEY (`codigoCirugia`)
    REFERENCES `appSchema`.`cirugia` (`idcirugia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS anne;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'anne' IDENTIFIED BY 'anne123456';

GRANT ALL ON `mydb`.* TO 'anne';
GRANT ALL ON `appSchema`.* TO 'anne';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'anne';
GRANT SELECT, INSERT, TRIGGER ON TABLE `appSchema`.* TO 'anne';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'anne';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `appSchema`.* TO 'anne';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'anne';
GRANT EXECUTE ON ROUTINE `appSchema`.* TO 'anne';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
